[[entities]]
entity_type = "YRobot"
faction = "Player"
position = [30.652, 0.0, -13.4873]
rotation = [0.0, -0.9987, 0.0, 0.0518]

[[entities]]
entity_type = "YRobot"
faction = "Enemy"
position = [4.9224, 0.0, -13.6717]
rotation = [0.0, -0.7145, 0.0, 0.6996]

[[entities]]
entity_type = "MooseMan"
faction = "Enemy"
position = [11.312, 0.0, 8.1137]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeFoliage"
faction = "Static"
position = [-3.9293, 0.0, 14.0707]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeTrunk"
faction = "Static"
position = [-4.0707, 0.0, 13.9293]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeFoliage"
faction = "Static"
position = [19.1117, 0.0, 16.6127]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeTrunk"
faction = "Static"
position = [18.9703, 0.0, 16.4713]
rotation = [0.0, 0.0, 0.0, 1.0]
