[[entities]]
entity_type = "YRobot"
faction = "Player"
position = [38.9813, 0.0, -5.0717]
rotation = [0.0, -0.6743, 0.0, 0.7385]

[[entities]]
entity_type = "YRobot"
faction = "Enemy"
position = [-20.2221, 0.0, -16.5031]
rotation = [0.0, 0.6915, 0.0, 0.7224]

[[entities]]
entity_type = "MooseMan"
faction = "Enemy"
position = [-0.0397, 0.0196, 3.8416]
rotation = [0.0, -0.9923, 0.0, 0.1238]

[[entities]]
entity_type = "TreeFoliage"
faction = "Static"
position = [-3.9293, 0.0, 14.0707]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeTrunk"
faction = "Static"
position = [-4.0707, 0.0, 13.9293]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeFoliage"
faction = "Static"
position = [19.1117, 0.0, 16.6127]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "TreeTrunk"
faction = "Static"
position = [18.9703, 0.0, 16.4713]
rotation = [0.0, 0.0, 0.0, 1.0]
